minimumReleaseAge: 10080
minimumReleaseAgeIgnoreMissingTime: true

blockExoticSubdeps: true

resolutionMode: highest

trustPolicy: no-downgrade
trustPolicyExclude:
  - 'semver@6.3.1'

allowBuilds:
  esbuild: true
